# -*- coding: utf-8 -*-
"""VTQS_ANALYSIS_NEW_2025_SCIENCE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcYf9fbFiuO5gIoxV5HUbti3KSrXa4YA
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv("Data_Frame_VTQS.csv")



# Teniamo solo i trial DP dove Visual_error è definito (non NaN)
df_dp = df[df["Trial_type_label"] == "DP"].copy()
df_dp = df_dp.dropna(subset=["Visual_error"])

# Convertiamo Visual_error in intero (0/1)
df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)

# Seleziona le feature da usare per predire (puoi modificarle/espanderle)
features = ["Tactile_stimulus", "Visual_stimulus", "Condition_label"]

# One-hot encoding delle variabili categoriche (es. Condition_label)
X = pd.get_dummies(df_dp[features], drop_first=True)

# Target: Visual_error
y = df_dp["Visual_error"]



# Rimuove righe con infiniti o NaN
import numpy as np
X = X.replace([np.inf, -np.inf], np.nan).dropna()
y = y.loc[X.index]  # Allinea il target dopo il drop

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Crea e allena il modello
clf = RandomForestClassifier(class_weight="balanced", random_state=42)
clf.fit(X_train_scaled, y_train)

!pip install -q imbalanced-learn

from imblearn.over_sampling import SMOTE

# Applica SMOTE sul training set
smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train_scaled, y_train)

# Controlla il bilanciamento
import numpy as np
unique, counts = np.unique(y_train_bal, return_counts=True)
print(dict(zip(unique, counts)))

clf_bal = RandomForestClassifier(n_estimators=100, random_state=42)
clf_bal.fit(X_train_bal, y_train_bal)

y_pred_bal = clf_bal.predict(X_test_scaled)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_bal))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_pred_bal)
ConfusionMatrixDisplay(cm).plot()

# Importanza delle feature dal modello
importances = clf_bal.feature_importances_
feature_names = X.columns

# Ordina le feature per importanza
feat_imp = pd.Series(importances, index=feature_names).sort_values()

# Plot
plt.figure(figsize=(8, 5))
feat_imp.plot(kind='barh')
plt.xlabel("Importanza")
plt.title("Importanza delle feature – Random Forest")
plt.tight_layout()
plt.show()

cm = confusion_matrix(y_test, y_pred_bal)
ConfusionMatrixDisplay(cm).plot()

from sklearn.metrics import roc_curve, roc_auc_score

# Probabilità predette per classe 1
y_prob = clf_bal.predict_proba(X_test_scaled)[:, 1]

# Calcola ROC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
auc_score = roc_auc_score(y_test, y_prob)

# Plot
plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f"AUC = {auc_score:.2f}")
plt.plot([0, 1], [0, 1], "--", color="gray")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve – Visual Error Classifier")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Calcola la media di Visual_error per punto tattile (solo DP)
df_dp = df[df["Trial_type_label"] == "DP"].dropna(subset=["Visual_error"])
df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)

vc_by_point = df_dp.groupby("Tactile_stimulus")["Visual_error"].mean().reset_index()

# Plot
sns.barplot(data=vc_by_point, x="Tactile_stimulus", y="Visual_error")
plt.ylabel("Probability of Visual Capture")
plt.xlabel("Tactile Stimulation Point")
plt.title("Visual Capture Rate by Tactile Location")
plt.ylim(0, 1)
plt.tight_layout()
plt.show()

import pandas as pd
from scipy.stats import chi2_contingency

# Tabella 2xN: visual_error x tactile_stimulus
contingency_table = pd.crosstab(df_dp["Tactile_stimulus"], df_dp["Visual_error"])
print(contingency_table)

chi2, p, dof, expected = chi2_contingency(contingency_table)

print(f"Chi2 statistic: {chi2:.3f}")
print(f"p-value: {p:.4f}")
print(f"Degrees of freedom: {dof}")

df_dp["Combo"] = df_dp["Tactile_stimulus"].astype(str) + "-" + df_dp["Visual_stimulus"].astype(str)
df_dp.head()
df_dp.to_csv("df_dp2.csv")

combo_vc = df_dp.groupby("Combo")["Visual_error"].mean().sort_values(ascending=False)

# Mostra le top 10 combinazioni
print(combo_vc.head(10))

import seaborn as sns
plt.figure(figsize=(10, 6))
sns.barplot(x=combo_vc.index, y=combo_vc.values)
plt.xticks(rotation=90)
plt.ylabel("Visual Capture Rate")
plt.xlabel("Tactile - Visual Combination")
plt.title("Visual Capture by Tactile–Visual Stimulus Pair")
plt.tight_layout()
plt.show()

from scipy.stats import chi2_contingency

# Tabella di contingenza tra Combo e Visual_error
combo_table = pd.crosstab(df_dp["Combo"], df_dp["Visual_error"])
chi2, p, dof, _ = chi2_contingency(combo_table)
print(f"Chi² = {chi2:.2f}, p = {p:.4f}, df = {dof}")

import statsmodels.api as sm
import statsmodels.formula.api as smf

# Assicura che Visual_error sia binaria int
df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)

# Regressione logistica
model = smf.logit("Visual_error ~ C(Combo)", data=df_dp).fit()
print(model.summary())

from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey = pairwise_tukeyhsd(endog=df_dp["Visual_error"],
                          groups=df_dp["Combo"],
                          alpha=0.05)
print(tukey)

df_dp["Tactile_stimulus"] = df_dp["Tactile_stimulus"].astype(int)
df_dp["Visual_stimulus"] = df_dp["Visual_stimulus"].astype(int)
df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)
df_dp.head()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Calcola media (cioè percentuale di VC) per ogni combinazione
heat_data = df_dp.pivot_table(
    values="Visual_error",
    index="Tactile_stimulus",
    columns="Visual_stimulus",
    aggfunc="mean"
)

# Ordina se necessario
heat_data = heat_data.sort_index().sort_index(axis=1)

plt.figure(figsize=(6, 5))
ax = sns.heatmap(heat_data, annot=True, fmt=".2f", cmap="GnBu", cbar_kws={"label": "Vision-biased error Rate"})
plt.title("Vision-biased error rate by Visuo-tactile Stimulus Pair", fontsize=15)
plt.xlabel("Visual Stimulus Location", fontsize=13)
plt.ylabel("Tactile Stimulus Location", fontsize=13)
ax.invert_yaxis()
plt.tight_layout()
plt.show()

df_hand = df_dp[df_dp["Condition_label"] == "hand"].copy()

# Calcola media (cioè percentuale di VC) per ogni combinazione nella condizione 'hand'
heat_data_hand = df_hand.pivot_table(
    values="Visual_error",
    index="Tactile_stimulus",
    columns="Visual_stimulus",
    aggfunc="mean"
)

# Ordina se necessario (se i tuoi indici non sono già ordinati)
heat_data_hand = heat_data_hand.sort_index().sort_index(axis=1)

plt.figure(figsize=(6, 5))
ax_hand = sns.heatmap(heat_data_hand, annot=True, fmt=".2f",
                      cmap="YlGnBu", # O la colormap che preferisci
                      cbar_kws={"label": "Visual Capture Rate"})
plt.title("Visual Capture Rate (Condition: Hand)", fontsize=15)
plt.xlabel("Visual Stimulus Location", fontsize=13)
plt.ylabel("Tactile Stimulus Location", fontsize=13)
ax_hand.invert_yaxis()
plt.tight_layout()
plt.show()

# --- Heatmap per la condizione 'cube' ---
df_cube = df_dp[df_dp["Condition_label"] == "cube"].copy()

# Calcola media (cioè percentuale di VC) per ogni combinazione nella condizione 'cube'
heat_data_cube = df_cube.pivot_table(
    values="Visual_error",
    index="Tactile_stimulus",
    columns="Visual_stimulus",
    aggfunc="mean"
)

# Ordina se necessario (se i tuoi indici non sono già ordinati)
heat_data_cube = heat_data_cube.sort_index().sort_index(axis=1)

plt.figure(figsize=(6, 5))
ax_cube = sns.heatmap(heat_data_cube, annot=True, fmt=".2f",
                      cmap="YlGnBu", # O la colormap che preferisci
                      cbar_kws={"label": "Visual Capture Rate"})
plt.title("Visual Capture Rate (Condition: Cube)", fontsize=15)
plt.xlabel("Visual Stimulus Location", fontsize=13)
plt.ylabel("Tactile Stimulus Location", fontsize=13)
ax_cube.invert_yaxis()
plt.tight_layout()
plt.show()

df_dp.head()

# Seleziona solo le colonne che ti servono
X = df_dp[["Combo", "Condition_label"]]
y = df_dp["Visual_error"].astype(int)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Codifica Combo e Condition in dummy variables
encoder = ColumnTransformer(
    transformers=[("onehot", OneHotEncoder(drop='first'), ["Combo", "Condition_label"])],
    remainder="drop"
)

X_encoded = encoder.fit_transform(X)

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# Split dei dati
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42, stratify=y)

# Applica SMOTE sul training set
smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_bal, y_train_bal)

from sklearn.metrics import classification_report, roc_auc_score

y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print(f"AUC = {roc_auc_score(y_test, y_prob):.2f}")

import pandas as pd
import matplotlib.pyplot as plt

# Ottieni i nomi delle feature codificate
feature_names = encoder.get_feature_names_out(["Combo", "Condition_label"])
importances = clf.feature_importances_

# Serie ordinata
feat_imp = pd.Series(importances, index=feature_names).sort_values()

# Plot
plt.figure(figsize=(8, 5))
feat_imp.plot(kind='barh')
plt.xlabel("Importance")
plt.title("Feature Importance – Combo-based Random Forest")
plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm).plot()
plt.title("Confusion Matrix – Combo Model")
plt.tight_layout()
plt.show()

from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, y_prob):.2f}")
plt.plot([0, 1], [0, 1], "--", color="gray")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve – Combo Model")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Filtro: solo DP
dp = df_dp[df_dp["Trial_type_label"] == "DP"].copy()

# Assicura tipi
dp["Visual_error"] = dp["Visual_error"].astype(int)
dp["Error"] = dp["Error"].astype(int)

# Raggruppa per soggetto e condizione
grouped = dp.groupby(["ID", "Condition_label"]).agg({
    "Visual_error": "mean",
    "Error": "mean"
}).unstack().reset_index()

# Rinomina colonne
grouped.columns = ["ID",
                   "Total_error_rate_cube", "Total_error_rate_hand",
                   "Visual_capture_rate_cube", "Visual_capture_rate_hand"]

# Riordina colonne
df_profile = grouped[["ID",
                      "Total_error_rate_hand", "Total_error_rate_cube",
                      "Visual_capture_rate_hand", "Visual_capture_rate_cube"]]

df_profile.head()

df.head()

dp.groupby(["ID", "Condition_label"]).size()

from sklearn.preprocessing import StandardScaler

# Rimuovi la colonna ID (ci serve solo per riferimento)
features = df_profile.drop(columns="ID")

# Standardizza
scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

from sklearn.cluster import KMeans

# Proviamo con 3 cluster
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

# Aggiungiamo l'etichetta al profilo
df_profile = df_profile.copy()
df_profile["Cluster"] = clusters

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Riduci a 2 componenti per il plot
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(7, 6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters, cmap="viridis", s=60)
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("Participant Clusters (K-means, DP trials)")
plt.grid(True)
plt.tight_layout()
plt.show()



from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Prova k da 1 a 10
inertias = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertias.append(kmeans.inertia_)

# Plot
plt.figure(figsize=(7, 5))
plt.plot(K_range, inertias, marker='o')
plt.title("Elbow Method - Optimal Number of Clusters")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Inertia (Within-cluster SSE)")
plt.xticks(K_range)
plt.grid(True)
plt.tight_layout()
plt.show()

# Calcola le medie per cluster
cluster_summary = df_profile.groupby("Cluster").mean(numeric_only=True).round(3)
cluster_summary

df_profile["Cluster"].value_counts()

df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)
df_dp["Condition_label"] = df_dp["Condition_label"].astype("category")

import statsmodels.formula.api as smf

# Regressione logistica binaria
logit_model = smf.logit("Visual_error ~ Trial_Index * Condition_label", data=df_dp)
result = logit_model.fit()
print(result.summary())

# Crea colonna per binning temporale (2 metà)
df_dp["Time_block"] = pd.cut(df_dp["Trial_Index"], bins=[0, 48, 96], labels=["early", "late"])

# Assicura che le variabili siano della classe corretta
df_dp["Time_block"] = df_dp["Time_block"].astype("category")
df_dp["Condition_label"] = df_dp["Condition_label"].astype("category")
df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)

# Regressione logistica con interazione
import statsmodels.formula.api as smf
model = smf.logit("Visual_error ~ Time_block * Condition_label", data=df_dp).fit()
print(model.summary())

df_dp.to_csv("ecco.csv")

import pandas as pd

# Filtra solo i trial DP
df_dp = df[df["Trial_type_label"] == "DP"].copy()

# Ordina i dati per soggetto, condizione e Trial_Index
df_dp.sort_values(by=["ID", "Condition_label", "Trial_Index"], inplace=True)

# Crea un indice sequenziale per i trial DP per soggetto e condizione
df_dp["DP_index"] = df_dp.groupby(["ID", "Condition_label"]).cumcount()

# Definisce il blocco temporale: primi 8 trial come 'early', ultimi 8 come 'late'
df_dp["Time_block"] = pd.cut(df_dp["DP_index"], bins=[-1, 7, 15], labels=["early", "late"])

# Assicura tipi corretti
df_dp["Visual_error"] = df_dp["Visual_error"].astype(int)
df_dp["Time_block"] = df_dp["Time_block"].astype("category")
df_dp["Condition_label"] = df_dp["Condition_label"].astype("category")

# Regressione logistica
model = smf.logit("Visual_error ~ Time_block * Condition_label", data=df_dp).fit()
print(model.summary())

df_dp.head()

df_dp.to_csv("DP_DF.csv")

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

model = smf.logit("Visual_error ~ DP_index * Condition_label", data=df_dp).fit()
print(model.summary())





df.head()

import pandas as pd
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

tsne = TSNE(n_components=2, random_state=42)
tsne_results = tsne.fit_transform(X_scaled)

import matplotlib.pyplot as plt
from scipy.spatial import ConvexHull
import numpy as np
import matplotlib.cm as cm

# Numero di cluster unici
unique_clusters = np.unique(clusters)
n_clusters = len(unique_clusters)

# Colori dalla colormap viridis
colors = cm.get_cmap("viridis", n_clusters)

plt.figure(figsize=(7, 6))

# Disegna punti e contorni cluster
for i, cluster_id in enumerate(unique_clusters):
    points = tsne_results[clusters == cluster_id]
    plt.scatter(points[:, 0], points[:, 1], s=60, color=colors(i), label=f"Cluster {cluster_id}")

    if len(points) >= 3:
        hull = ConvexHull(points)
        hull_pts = points[hull.vertices]
        plt.fill(hull_pts[:, 0], hull_pts[:, 1], color=colors(i), alpha=0.3)  # Area trasparente
        for simplex in hull.simplices:
            plt.plot(points[simplex, 0], points[simplex, 1], color=colors(i), lw=1.5)

plt.xlabel("tSNE 1", fontsize = 13)
plt.ylabel("tSNE 2", fontsize = 13)
plt.title("Participant Clusters", fontsize = 16)
plt.legend()
plt.tight_layout()
plt.show()

df_profile.head()